apiVersion: v1
kind: Secret
metadata:
  name: chaincommand-secret
  namespace: chaincommand
  labels:
    app.kubernetes.io/name: chaincommand
type: Opaque
data:
  CC_API_KEY: REPLACE_WITH_BASE64_ENCODED_VALUE
  CC_OPENAI_API_KEY: REPLACE_WITH_BASE64_ENCODED_VALUE
  DATABASE_URL: REPLACE_WITH_BASE64_ENCODED_VALUE
  REDIS_URL: REPLACE_WITH_BASE64_ENCODED_VALUE
  POSTGRES_PASSWORD: REPLACE_WITH_BASE64_ENCODED_VALUE
